### ISSUE TITLE
Clean up app/actions folder using ESLint

### ISSUE THREAD

**Issue by cannawen** [odota/mobile#108]
### Introduction
ESLint is a developer tool that flags any code that does not follow certain rules outlined in the `.eslintrc.json` file (i.e. all declared variables should be used). 

This issue is to use ESLint to scan through the `app/actions` directory and fix any lint warnings that should obviously be fixed, or comment below with any lint warnings that need further discussion*.

### Skills
Basic familiarity with JavaScript and programming
This issue would be a good fit for those new to this project or open source in general.

### Instructions
In `package.json`, add a new script `"actions-lint": "eslint app/actions"`
Run `npm run actions-lint` in your command line to view warnings that ESLint generates

---
*Since this is the first lint-warning-fixing issue opened, I'll start us off with some topics of discussion

---
Pease comment below if you would like to volunteer to contributing code and fix these lint warnings!

**Comment by cannawen** [comment]
## Topics of Discussion
### console.log
There are quite a few warnings about `console.log` statements. 

Should console.log statements in production code? 

Most of them seem to be for logging errors, but perhaps we could use console.error instead, and allow for `console.error` statements but not `console.log` statements? 

Or remove the "no-console" rule from ESLint all together if we don't mind logs?

[See ESLint documentation for no-console rule](https://eslint.org/docs/rules/no-console)

### `limit` parameter not used
In `player_heroes_act.fetchHeroes` the `limit` parameter is defined, but never used.

Do we want to remove the parameter? Or start using it?

---
The rest of the errors seem pretty straightforward to fix, but please comment below if I missed any warnings that need further discussion.

**Comment by Proyoyo** [comment]
Regarding console.log, we can change it into console.error instead.

We can remove the limit parameter in player.heroes.act (fetchHeroes).

For some reason GitHub didn't send me any email notification when a new issue is created. I just saw this today.

**Comment by Proyoyo** [comment]
Implemented in ea055ace534a87a307dd02008b0b817bad558b20
