### ISSUE TITLE
iOS StatusBar light-content not working

### ISSUE THREAD

**Issue by Proyoyo** [odota/mobile#110]
On iOS, StatusBar always reverted back to default (dark-content) even after setting it in the NavBar.

**Comment by Adis** [comment]
In your Info.plist, set the "View controller-based status bar appearance" to NO (it might be missing, so add a new key), then in the General tab, set the status bar style to light-content.

**Comment by Proyoyo** [comment]
@Adis it's still doesn't work. I think it's related to this bug: https://github.com/aksonov/react-native-router-flux/issues/2882

**Comment by mdelclaro** [comment]
Did you try this?
`<StatusBar barStyle="light-content"/>`

**Comment by Proyoyo** [comment]
@mdelclaro Yeah I already tried that. I can't test it at the moment but I think this might have something to do with https://github.com/react-native-community/react-native-navbar having it's own StatusBar. The best way to fix this is to remove react-native-navbar component and use our own React Component as the custom navigation bar.
