### ISSUE TITLE
Theme not persisted in settings screen

### ISSUE THREAD

**Issue by dkwl93** [odota/mobile#111]
The settings screen should persist the chosen theme
Repro:
1. Go to settings
2. Set a theme
3. Navigate to different page
4. Go back to settings
5. Notice the radio button for the theme you selected is not checked anymore

**Comment by nersoh** [comment]
Same issue here. I think I found the problem, so I'll try to create a PR soon.

**Comment by dkwl93** [comment]
Cheers @nersoh
