### ISSUE TITLE
CocoaPods-installed source (./ios/Pods) should be .gitignore'd

### ISSUE THREAD

**Issue by keatongreve** [odota/mobile#115]
As someone who develops in a lot of iOS/macOS apps, I think it's best to put `Pods/` directories in your repo's .gitignore. When `Podfile`s are set up correctly, `pod install` should work consistently across all environments. In addition, keeping that out of your git history will keep your git database much lighter in the long run.

Just a suggestion though, feel free to close if you disagree. Looking forward to contributing!

**Comment by Adis** [comment]
`pod install` doesn't work consistently though since you can't guarantee the gem version to be exactly the same across all machines. Considering possible API changes, it's much better to be able to revert all pod versions to a previous commit and working state, which is usually the reason why e.g. gitignore.io doesn't do it automatically any more.

**Comment by keatongreve** [comment]
You can use a Gemfile to make sure the version of `pod` used is consistent. Also, the `pod` version is printed at https://github.com/odota/mobile/blob/e6eef63fc6c3a6e07fe2c104b50bf82304ee3b53/ios/Podfile.lock#L24

**Comment by Adis** [comment]
Too much effort for something that git gives for free. I prefer having a running project after a checkout far more than having a smaller repo. That, and making sure any other dependencies (ruby version, cocoapods gem) can be a hassle to setup if you use any form of automation or CI/CD.

**Comment by keatongreve** [comment]
I think that's a fair point, especially for smaller projects with a few CocoaPods dependencies, like this one.

> having a running project after a checkout

Don't forget that this is a React Native app, and you still need to run `npm/yarn install`.

**Comment by Proyoyo** [comment]
Closing this one for now.
