### ISSUE TITLE
Login page is blank on Android

### ISSUE THREAD

**Issue by bobsaget4lyfe** [odota/mobile#119]
[https://imgur.com/gallery/WBX80](url)

**Comment by Proyoyo** [comment]
@bobsaget4lyfe Hey there, can I get your steam nickname & device type?

**Comment by Proyoyo** [comment]
And also your Android version if possible.

**Comment by bobsaget4lyfe** [comment]
@Proyoyo Hi mate it is working now.
- Nick: The thoroughbred of sin
- device type: S7
- Android version: 7.0

**Comment by Proyoyo** [comment]
Closing this issue as it's fixed.
