### ISSUE TITLE
When going to next page, screen should scroll back to top

### ISSUE THREAD

**Issue by cannawen** [odota/mobile#127]
Expected: 
On Matches, Heroes, and Peers pages, when a user clicks `<` or `>`, they should be navigated back to the top of the page.

Actual:
The user is left viewing the bottom of the screen

**Comment by ganes1410** [comment]
@cannawen  @Proyoyo  Is someone doing this? if not can you help me get started with this.

**Comment by Proyoyo** [comment]
@ganes1410 I'm not working on this issue at the moment. Sure thing. How can I help you?

**Comment by ganes1410** [comment]
![screenshot_1530852211](https://user-images.githubusercontent.com/16988745/42360259-5f40fb94-8105-11e8-884b-0ec0d3fa5b62.png)

@Proyoyo  is this the page are we talking about ?

**Comment by Proyoyo** [comment]
@ganes1410 It should be the Matches page. You need to click Matches on the bottom navigation bar.

**Comment by ganes1410** [comment]
@Proyoyo  I made a fix.can i make a pr?

**Comment by ganes1410** [comment]
@Proyoyo  I made a fix.I will make a pr

**Comment by Proyoyo** [comment]
Sure thing. Can you add me as the reviewer in the PR?

**Comment by ganes1410** [comment]
@Proyoyo  i don't i can add a reviewer

**Comment by Proyoyo** [comment]
Merged @ganes1410

**Comment by ganes1410** [comment]
Cool @Proyoyo
