### ISSUE TITLE
About ios jump url after steam authorize success

### ISSUE THREAD

**Issue by qiu198022** [odota/mobile#143]
I have setup a web and steam authorize success and jump to domain/players/xxx successfully.
But when I compile and run of the mobile project.
I modify the LoginPage.js some configure source code
const opendotaURL = 'https://api.opendota.com/login/';
if(splitted[2] == "www.opendota.com" && !this.state.redirecting) {
to 
const opendotaURL = 'http://domain:5000/login/';
if(splitted[2] == "www.domin.com:3000" && !this.state.redirecting) {

After I login in the steam success the ios app, it jump to the webpage in browser style not the reactive native style with nav at bottom.
How could I jump to the native mode in the reactive native ios project after steam authorize?
By the way I want to move nav "Overview Matches Heroes Peers"at bottom to the top how could i modify because it have been covered by my tabbar-control?

![image](https://user-images.githubusercontent.com/51344/51455075-d5b6ed00-1d82-11e9-90a0-e2115c12e2c1.png)
  
![image](https://user-images.githubusercontent.com/51344/51455105-fe3ee700-1d82-11e9-846a-9ebbfc812c0f.png)

![image](https://user-images.githubusercontent.com/51344/51455170-465e0980-1d83-11e9-83ef-1432bb51990f.png)

**Comment by qiu198022** [comment]
I found the tabbar configure at the source code
<ScrollableTabView tabBarPosition="bottom"
but still don't known how to make the jump native after authorize successfully

**Comment by Proyoyo** [comment]
@qiu198022 We're using react-native-router-flux library for the app navigation.
The code that we're using to navigate to Home Page after successful authentication is` Actions.home();`

**Comment by qiu198022** [comment]
I have add some log and debug the LoginPage.js. But I found the onNavigationStateChange(navState)
have not been triggered after the steam authorize successfully。And it open the web browser not trigger Actions.home() to go to react native.

class LoginPage extends Component {

    constructor(props) {
        super(props);
        this.state = {
            'redirecting': false
        }
        console.log('constructor');
    }

    componentDidMount() {
        this.props.tracker.trackScreenView('Login');
        console.log('Login');
    }

    onNavigationStateChange(navState) {
    	console.log('onNavigationStateChange');
        var splitted = navState.url.split("/");

<img width="695" alt="2019-01-22 2 48 48" src="https://user-images.githubusercontent.com/51344/51517423-9b6a5000-1e55-11e9-9452-8caa61811922.png">

**Comment by qiu198022** [comment]
![image](https://user-images.githubusercontent.com/51344/51517485-dc626480-1e55-11e9-8eb3-220cc319127c.png)
The Console display some information about Unable to open URL about:blank

**Comment by Proyoyo** [comment]
@qiu198022 
I'm not sure what the issue is because the code that's currently on this Github is working fine.
Also I'm not sure what you're trying to achieve.
