### ISSUE TITLE
Rank supports 7 star system but app only supports 5

### ISSUE THREAD

**Issue by dkwl93** [odota/mobile#144]
Rank has 7 stars but app only has 5. App should be updated to reflect new system. Image assets should be imported from the opendota/web repo

**Comment by howardchung** [comment]
@Proyoyo? If you're busy I can try to make the change, I don't have a RN dev environment set up though.

**Comment by Proyoyo** [comment]
I can work on this sometime next week. There's a big release this past month at work so I've been a bit busy.

**Comment by dkwl93** [comment]
HMU @Proyoyo if you don't have the time. I can handle this one too if need be

**Comment by Proyoyo** [comment]
@dkwl93 Do you mind taking care of this one? I'm still a bit busy this week.
