### ISSUE TITLE
Update buildscript.ext.googlePlayServicesVersion to lockdown to a specific version

### ISSUE THREAD

**Issue by dkwl93** [odota/mobile#146]
https://github.com/odota/mobile/blob/master/android/build.gradle

googlePlayServicesVersion is currently set to download the latest version. Google released a breaking change yesterday which may mean that builds will fail. 

We should lock down the versions of googlePlayServicesVersion to ensure that we don't reference the latest (breaking) version of google play services

Release: https://developers.google.com/android/guides/releases

Issue: https://github.com/facebook/react-native/issues/25293

CC: @Proyoyo @kelset

**Comment by Proyoyo** [comment]
Thanks for the heads up.

**Comment by dkwl93** [comment]
This has been shipped
