### ISSUE TITLE
Change json references to dotaconstants

### ISSUE THREAD

**Issue by Proyoyo** [odota/mobile#35]
Change json references to dotaconstants. Currently the json constants are copied manually from odota/ui repo.

**Comment by maferland** [comment]
What do you want exactly ?

**Comment by Proyoyo** [comment]
To get the value of heroes.json, items.json, abilities.json, etc from dotaconstants npm package instead of from manually copied files in the json folder.

**Comment by maferland** [comment]
Okay, not sure I will have the time soon. I will let you know if I start it. By the way, you made a typo in the labels. hacktobervest => hacktoberfest. Cheers!

**Comment by Proyoyo** [comment]
Cheers! Fixed the labels.

**Comment by Proyoyo** [comment]
Implemented in #76
