### ISSUE TITLE
Implement Heatmap

### ISSUE THREAD

**Issue by Proyoyo** [odota/mobile#55]
Implement Heatmap with heatmap.js and webview. Currently it's WIP.

**Comment by vocosu** [comment]
Got a start on this already. Will update end of week with progress.

**Comment by vocosu** [comment]
Finished the heatmap. Looks fine on my Samsung Galaxy S7, not sure about other devices

https://www.opendota.com/matches/3538474686/laning

![screenshot_20171116-201258](https://user-images.githubusercontent.com/7953198/32929240-8751e7ca-cb0b-11e7-8008-efdc615d418a.png)
![screenshot_20171116-201322](https://user-images.githubusercontent.com/7953198/32929241-889fcb6a-cb0b-11e7-8bb7-db7c981e548e.png)
![screenshot_20171116-201306](https://user-images.githubusercontent.com/7953198/32929242-89cc5724-cb0b-11e7-9b7e-9bcfd1485c59.png)

**Comment by Proyoyo** [comment]
Great job!
Let me know when you’re ready to submit a PR for it. I have a friends wedding this weekend so the earliest that I can review the PR is Monday AU time (should be Sunday evening in US).

**Comment by Proyoyo** [comment]
@vocosu Left some comment on your PR. It seems that there's some problem in iOS. Do you have access to Xcode?

**Comment by Proyoyo** [comment]
Implemented in #101
