### ISSUE TITLE
Table Sorting

### ISSUE THREAD

**Issue by Proyoyo** [odota/mobile#6]
Table needs to be sorted when a user clicks on a header

**Comment by dricholm** [comment]
Is this still available?
If yes, I can take a look at it.

**Comment by vocosu** [comment]
I can take a shot at this. What table columns do you want sortable?

**Comment by Proyoyo** [comment]
For the moment, probably "Ended", "Length" and "K/D/A". @vocosu

**Comment by vocosu** [comment]
@Proyoyo This is what I have so far for table sorting on my fork: https://github.com/vocosu/mobile/commit/d0d863649f680d54d3ed4d948d642e308207f1ba 

Will clean it up later and also implement it for the other components.

Let me know if I'm on the right track, new to React Native (but familiar with React) and just starting to get familiar with this project's code base.

**Comment by Proyoyo** [comment]
Closing this as this is implemented in #78
