### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Proyoyo** [odota/mobile#8]
Implement login to replace search & set profile

**Comment by Proyoyo** [comment]
Blocked until there's Open ID library for react-native

**Comment by howardchung** [comment]
Do you need an OpenID library?  Is it possible to open api.opendota.com/login in a web view, then access the cookie that's saved to the browser?

**Comment by Proyoyo** [comment]
Yeah, need an OpenID library for this. I've tried a few for react native and none of them worked. I haven't tested it using webview yet. I'll try that once I'm done with the match details page.

**Comment by howardchung** [comment]
Preferably it would be integrated with the OpenDota login state, so using the mobile app counts toward the inactivity check. (this isn't strictly required, though, and I don't think we have any other state)
