### ISSUE TITLE
Home shows wrong Profile

### ISSUE THREAD

**Issue by elklopso** [odota/mobile#86]
Hey,

I started the App, went to my played games, picked a random game, and there a random Profile. Here I can see what I want, but when I go the way back with my back buttom it goes the following way:
Game -> My Games List -> The Profile I just watched with his stats for Heroes and so on. 
I can swap to my favorites and click on Home again, but the wrong Profile stays. 
This is on Android.

**Comment by Proyoyo** [comment]
Fixed the Android back button bug in #103
