### ISSUE TITLE
Can back-button into Splash Screen

### ISSUE THREAD

**Issue by jhonnold** [odota/mobile#87]
Upon loading into the App if I hit the back button I will get stuck in the Splash Screen. Also if I rotate my phone on this screen the blue background rotates with it which causes white/blue background.

**Comment by jhonnold** [comment]
If possible I've worked in react native and would like to resolve both these issues.

**Comment by Proyoyo** [comment]
Hey @jhonnold, sure thing! You can submit a PR to fix these issues. You can also head to our Discord and have a chat in the #mobile channel.
