### ISSUE TITLE
App crashes when accessing 'Performances' under Match Details

### ISSUE THREAD

**Issue by marktoh** [odota/mobile#93]
I'm using an iPhone 6

**Comment by Proyoyo** [comment]
Hi @marktoh, can I get more information about this? Does this happen on all matches? Or is it a specific match?

If it's a specific match, can I get the match ID?

**Comment by marktoh** [comment]
Hello @Proyoyo , it is happening on all matches. Please let me know if there is any more information that I can provide to help solve the issue.

**Comment by Proyoyo** [comment]
@marktoh Can you send me your player name/steam ID via Reddit/Discord PM? It'll help in investigating this issue because as far as I know, this doesn't happen to anyone else.

**Comment by Proyoyo** [comment]
I can't replicate this issue. It's closed until I can get further information.
