### ISSUE TITLE
Upcoming matches

### ISSUE THREAD

**Issue by vitbulio** [odota/mobile#97]
Hello! How can I get upcoming matches? Is it possible? There's only matches history(

**Comment by howardchung** [comment]
Unfortunately there are no Valve APIs for upcoming matches that I know about.  Several sites maintain their own calendars, but they're not official.

**Comment by vitbulio** [comment]
@howardchung thanks a lot!

**Comment by vitbulio** [comment]
@howardchung What do you think about this method from Stream Api? "Matches" GET method with parameters ("from" - Integer, Minimum timestamp) and ("to" - Integer, Max timestamp).

**Comment by howardchung** [comment]
I don't think it will return matches in the future
