### ISSUE TITLE
npm install warning (...requires a peer of react... but none was installed)

### ISSUE THREAD

**Issue by cannawen** [odota/mobile#98]
I'm getting a warning when running `npm install`
```
npm WARN mobx-react@4.3.5 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0 but none was installed.
npm WARN react-static-container@1.0.2 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0 but none was installed.
```

I ran `rm -rf node_modules` and a clean `npm install` but I'm still seeing the warnings. Is anyone else experiencing this? Any ideas?

Mac OSX 10.11.6
npm version 4.6.1

**Comment by doubledsuarez** [comment]
I'm on MacOS 10.13.2 and I did not get this issue, but I used `yarn install` instead of `npm install`. Have you tried using that? You can easily install yarn using homebrew with the command `brew install yarn`.

**Comment by howardchung** [comment]
In general npm might have some warnings depending on your particular environment/packages installed.

Unless they are errors they should not affect the functionality.

**Comment by howardchung** [comment]
In this case it might be caused by the package.json listing:
`    "react": "16.0.0-alpha.12",`

React 16 should have a stable release now, @Proyoyo perhaps it can be upgraded?

**Comment by Proyoyo** [comment]
Updated to React 16.2 & ReactNative 0.52. Those warnings should not appear now.
